### ISSUE TITLE
Load test needs a warm up phase.

### ISSUE THREAD

**Issue by whitingjr** [jimma/frdemo-loadtest#1]
To get realistic results for a JVM application a load test should include a warm up phase. Which is discarded from final performance results. Due to Hotspot compilation and profiling of the application to identify hot code paths.
 The Hyperfoil file [hyperfoil/frdemo.hf.yaml](https://github.com/jimma/frdemo-loadtest/blob/main/hyperfoil/frdemo.hf.yaml) should be updated to include the warm up phase at the beginning. A duration of 30 to 60 seconds should be sufficient. At a moderate to high load.
 After this phase a steady state/measurement phase is use for producing final results. Again 60 seconds is sufficient for a simple application.

**Comment by jimma** [comment]
@whitingjr  Could you please look at if this change is good for warm up?  https://github.com/jimma/frdemo-loadtest/pull/2/files

**Comment by whitingjr** [comment]
Yes that is perfect.
